# Generated by Django 4.2 on 2023-04-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhyrexianWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyrexian', models.CharField(max_length=255)),
                ('phonetic', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhyrexianWordNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('phyrexian_word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.phyrexianword')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=255)),
                ('phyrexian_text', models.TextField()),
                ('english_text', models.TextField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='words.card')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='words.exampletext')),
                ('phyrexian_word_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='words.phyrexianword')),
            ],
        ),
        migrations.CreateModel(
            name='CompositeBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='words.phyrexianword')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parents', to='words.phyrexianword')),
            ],
        ),
    ]
