# Generated by Django 4.2 on 2023-04-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compositebridge',
            old_name='child_id',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='compositebridge',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='examplebridge',
            old_name='example_text_id',
            new_name='example_text',
        ),
        migrations.RenameField(
            model_name='examplebridge',
            old_name='phyrexian_word_id',
            new_name='phyrexian_word',
        ),
        migrations.RenameField(
            model_name='exampletext',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='phyrexianwordnotes',
            old_name='phyrexian_word_id',
            new_name='phyrexian_word',
        ),
    ]
