# Generated by Django 4.2 on 2023-05-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_rename_child_id_compositebridge_child_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phyrexianword',
            old_name='translation',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='phyrexianword',
            old_name='phonetic',
            new_name='ipa',
        ),
        migrations.AddField(
            model_name='phyrexianword',
            name='latin',
            field=models.CharField(default='placeholderLatin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phyrexianword',
            name='official',
            field=models.CharField(default='placeholderOfficial', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compositebridge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='child_relationships', to='words.phyrexianword'),
        ),
        migrations.AlterField(
            model_name='compositebridge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent_relationships', to='words.phyrexianword'),
        ),
        migrations.AlterField(
            model_name='examplebridge',
            name='example_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bridges', to='words.exampletext'),
        ),
        migrations.AlterField(
            model_name='examplebridge',
            name='phyrexian_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bridges', to='words.phyrexianword'),
        ),
        migrations.AlterField(
            model_name='exampletext',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='texts', to='words.card'),
        ),
        migrations.AlterField(
            model_name='phyrexianwordnotes',
            name='phyrexian_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='words.phyrexianword'),
        ),
    ]
